CREATE PLUGGABLE DATABASE WIND
  ADMIN USER dbadmin IDENTIFIED BY dbadmin
  ROLES = (DBA)
  DEFAULT TABLESPACE users
  FILE_NAME_CONVERT = (
    '/opt/oracle/oradata/ORCLCDB/pdbseed/',
    '/opt/oracle/oradata/ORCLCDB/WIND/'
  );
ALTER PLUGGABLE DATABASE WIND OPEN;
ALTER PLUGGABLE DATABASE WIND SAVE STATE; 

ALTER SESSION SET CONTAINER=WIND;

-- Create tablespace --
CREATE TABLESPACE BLOBS LOGGING DATAFILE '/opt/oracle/oradata/ORCLCDB/WIND/BLOB01.dbf' SIZE 1000M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE INDX LOGGING DATAFILE '/opt/oracle/oradata/ORCLCDB/WIND/INDX01.dbf' SIZE 1000M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE WCAUDIT LOGGING DATAFILE '/opt/oracle/oradata/ORCLCDB/WIND/WCAUDIT.dbf' SIZE 1000M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE USERS LOGGING DATAFILE '/opt/oracle/oradata/ORCLCDB/WIND/USERS01.dbf' SIZE 1000M AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER dbuser IDENTIFIED BY dbuser DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;


ALTER USER dbuser QUOTA UNLIMITED ON BLOBS;
ALTER USER dbuser QUOTA UNLIMITED ON INDX;
ALTER USER dbuser QUOTA UNLIMITED ON WCAUDIT;

grant unlimited tablespace to dbuser;
grant resource to dbuser;
grant Create Sequence to dbuser;
grant Create View to dbuser;
grant Create Session to dbuser;